r1:
  location: wooftywoo, 1033.500, 67.000, 1579.500
  lines:
  - '1'
  - '&9Welcome to the World of'
  - '&2MyneCraft&7 !'
r2:
  location: wooftywoo, 1050.500, 67.000, 1580.500
  lines:
  - '2'
  - '&eZeus&f, &3Hera&f, &4Hades&f, and &bPoseidon&f are the admins.'
  - Be sure and listen to them.
r3:
  location: wooftywoo, 1050.500, 67.000, 1597.500
  lines:
  - '3'
  - '&9Things To Do'
  - Minigames, Survival, Creative,
  - Adventure, Board Games, and more!
c5:
  location: wooftywoo, 1050.500, 67.000, 1782.500
  lines:
  - '5'
  - You can change your name with the &6/nick&f command.
  - '&9Example&f: &6/nick doofus&f.'
r4:
  location: wooftywoo, 1033.500, 67.000, 1598.500
  lines:
  - '4'
  - Stealing and griefing is
  - '&aALLOWED&f!'
r5:
  location: wooftywoo, 1033.500, 67.000, 1616.500
  lines:
  - '5'
  - Don't worry though, you can prevent griefing by
  - claiming land with a &egolden shovel&f.
r6:
  location: wooftywoo, 1050.500, 67.000, 1617.500
  lines:
  - '6'
  - The theme to the server is &9Ancient Greek Gods&f.
  - God positions are available to &aANYONE&f!
c6:
  location: wooftywoo, 1033.500, 67.000, 1783.500
  lines:
  - '6'
  - You can optionally choose to follow a god by using &6/follow <god>&f.
  - '&9Examples&f:&6 /follow zeus &7|&6 /follow hera &7|&6 /follow apollo &7|&6 etc'
r7:
  location: wooftywoo, 1050.500, 67.000, 1634.500
  lines:
  - '7'
  - You can find a &9list of all Gods&7
  - at &9/warp olympus&f, near the &9God statues&7.
c2:
  location: wooftywoo, 1033.500, 67.000, 1746.500
  lines:
  - '2'
  - You have unlimited use of &6/home <name>&f and &6/sethome <name>&f.
c3:
  location: wooftywoo, 1033.500, 67.000, 1764.500
  lines:
  - '3'
  - To see a list of homes from a player, use &6/home <player>:&f.
  - '&9Example&f: To see what homes Bitslane has, use &6/home Bitslane:&f.'
  - Don't forget the -> &6:&f <- at the end!
c4:
  location: wooftywoo, 1050.500, 67.000, 1765.500
  lines:
  - '4'
  - To actually visit, the syntax is &6/home <player>:<homeName>&f.
  - '&9Example&f: To visit Bitslane''s city: &6/home Bitslane:city&f.'
  - '&9Example&f: To visit missmandyy''s default home: &6/home missmandyy:home&f.'
c1:
  location: wooftywoo, 1050.500, 67.000, 1745.500
  lines:
  - '1'
  - Use the &6/help&f command to remind you in case
  - you forget anything you read in this hallway.
r8:
  location: wooftywoo, 1033.500, 67.000, 1635.500
  lines:
  - '8'
  - If a God becomes inactive for &91 day&f, those positions
  - become available to anyone.
  - '&eZeus&f, &3Hera&f, &4Hades&f, and &bPoseidon&f are exempt from expiration.'
r9:
  location: wooftywoo, 1033.500, 67.000, 1653.500
  lines:
  - '9'
  - Just ask &eZeus&f, &4Hades&f, or &bPoseidon&f to promote you to
  - an expired God positions. Use the command
  - '&6/seen <player> &fto check for expired God positions.'
r10:
  location: wooftywoo, 1050.500, 67.000, 1654.500
  lines:
  - '10'
  - What about swearing? Is that allowed?
  - FUCK YES IT IS YOU CUNT.
r11:
  location: wooftywoo, 1050.500, 67.000, 1671.500
  lines:
  - '11'
  - Everything on this server is &aFREE!
  - You will never pay for any of it.
r12:
  location: wooftywoo, 1033.500, 67.000, 1672.500
  lines:
  - '12'
  - Basically, &9don't be a jerk
  - and &4NO CHEATING! &fIt'll get you banned!
c7:
  location: wooftywoo, 1033.500, 67.000, 1801.500
  lines:
  - '7'
  - Just ask &eZeus&f, &4Hades&f, or &bPoseidon&f to promote you to
  - an expired God positions. Use the command
  - '&6/seen <player>&f to see if the player has been expired.'
c8:
  location: wooftywoo, 1050.500, 67.000, 1802.500
  lines:
  - '8'
  - Use &6/co i&f to see who placed/broke what blocks.
  - '&9Left-Click&f a block to check when it was first placed.'
  - '&9Right-Click&f to check block spaces that were removed/griefed.'
c9:
  location: wooftywoo, 1050.500, 67.000, 1819.500
  lines:
  - '9'
  - Use &6/warp&f by itself to list all the
  - warps across the server.
  - '&9Examples&f: &6/warp creative | /warp flat | /warp survival'
c10:
  location: wooftywoo, 1033.500, 67.000, 1820.500
  lines:
  - '10'
  - Use the &6/recipe <item>&f command to
  - look up recipes. Duh! lol
c11:
  location: wooftywoo, 1033.500, 67.000, 1838.500
  lines:
  - '11'
  - You can &6/pay <plr> <amt>&f, &6/sell hand&f, &6/balance&f
  - items and money. The &6/sell hand&f command sells
  - the entire stack of whatever you are holding.
c12:
  location: wooftywoo, 1050.500, 67.000, 1839.500
  lines:
  - '12'
  - 'Auctioning! First hold the item then use:'
  - '&6/auc <quantity> <price> <bid increment> <time>'
  - You can only auction in the overworld.
c13:
  location: wooftywoo, 1050.500, 67.000, 1856.500
  lines:
  - '13'
  - Need to know the item ID of something?
  - Use &6/wis &f!
spawnmessage:
  location: survival, 1.021, 73.700, -5.280
  lines:
  - '&2Welcome to &9MyneCraft&4!'
survival:
  location: spawn, 0.500, 12.200, -9.500
  lines:
  - '&2&lSurvival'
  - '&c(superheroes this way!)'
pvp:
  location: spawn, 0.500, 12.000, 10.500
  lines:
  - '&4&lPvP'
minigames:
  location: spawn, 9.500, 12.000, 0.500
  lines:
  - '&5&lMinigames'
creative:
  location: spawn, -9.500, 12.000, 0.500
  lines:
  - '&9&lCreative'
buildhub:
  location: flat, 325.500, 7.200, -314.500
  lines:
  - '&a&lCool Builds'
anarchy1:
  location: spawn, -55.500, 27.000, -85.500
  lines:
  - '&4&l&nYOU GET ONLY ONE COMMAND'
  - '&4&l&n/WARP ANARCHYSPAWN'
anarchy2:
  location: spawn, -59.500, 26.200, -85.500
  lines:
  - '&4&l&nYOU CAN''T PROTECT YOUR LAND'
anarchy3:
  location: spawn, -63.500, 26.200, -85.500
  lines:
  - '&4&l&nADMINS WILL NOT HELP YOU HERE'
anarchy5:
  location: spawn, -71.500, 26.200, -85.500
  lines:
  - '&4&l&nSINGLE PLAYER RULES AHEAD'
anarchy6:
  location: spawn, -75.500, 26.200, -85.500
  lines:
  - '&4&l&nREAD THESE AND DON''T BE STUPID'
anarchy4:
  location: spawn, -67.500, 26.200, -85.500
  lines:
  - '&4&l&nABSOLUTELY NO COMMANDS'
anarchy7:
  location: spawn, -75.500, 25.200, -85.500
  lines:
  - '&4&l&nTURN AROUND NOW'
superheroes:
  location: spawn, -9.500, 11.200, -39.500
  lines:
  - '&2&kI&cSuperheroes&2&kI'
  - '&2&kI&cIn Here&2&kI'
