# Simple Drugs Config.
Drugs:
  Toggle:
    wheat: true
    sugar: true
    paper: true
    gunpowder: true
    bone: true
    beet: true
    cactus: true
    wart: true
    announce: true
  Effect:
    length: 5220
  Console:
    logs: true
