#
# Remeber to read CrackShotPlus's wiki while configuring CrackShotPlus.
# https://www.spigotmc.org/wiki/crackshotplus-wiki/
#
# Set this to false if you don't want to generate default weapons on reload/restart.
GenerateDefaultWeapons: true
# Message which player gets when he has no permission for some command.
Permissions: '&a&lYou do not have permission to do this.'
# Message which player gets when he reloads config.
Configuration: '&a&lConfiguration reloaded.'
# Message which player gets when he does invalid command.
UnknownCommand: '&a&lInvalid command.'
# Message which player gets when he tries to zoom while in CREATIVE mode.
NoCreativeZooming: '&a&lYou cant zoom in CREATIVE mode.'
