AntiXRay:
  DebugMode: false
  NewPlayerStartingPoints: -400
  PointsEarnedPerHourPlayed: 800
  MaximumPoints: 1600
  IgnoreMaxPointsForBlockRatio: true
  ExemptCreativeModePlayers: true
  NotifyOnMiningLimitReached: true
  DefaultMaxHeight: 63
  Worlds:
    survival: ''
    survival_nether:
      DefaultMaxHeight: 256
    survival_the_end:
      DefaultMaxHeight: 256
    RabbitSeasonDuckSeason_nether:
      DefaultMaxHeight: 256
    wooftywoo_the_end:
      DefaultMaxHeight: 256
    pornhub: ''
    crapcakesandapplesauce_the_end:
      DefaultMaxHeight: 256
    anarchy: ''
    wooftywoo: ''
    creative: ''
    pornhub_nether:
      DefaultMaxHeight: 256
    wooftywoo_nether:
      DefaultMaxHeight: 256
    pornhub_the_end:
      DefaultMaxHeight: 256
    crapcakesandapplesauce: ''
    RabbitSeasonDuckSeason: ''
    flat: ''
    RabbitSeasonDuckSeason_the_end:
      DefaultMaxHeight: 256
    crapcakesandapplesauce_nether:
      DefaultMaxHeight: 256
  ProtectedBlockValues:
    EMERALD_ORE:
      Value: 50
      MaxHeight: 35
    DIAMOND_ORE:
      Value: 100
      MaxHeight: 20
