#########################
##      ChatterBot     ##
#########################

# Name displayed in ChatterBot's messages
ChatterBot-Name: kenpachi

# Format in which ChatterBot speaks
ChatterBot-Format: '&7[&eZ&7] %name%&f: %message%'

# Should messages players send ChatterBot be shown publicly?
Loud-Mode: false

# What is shown when a player ChatterBot a question (while on loud mode)
Loud-Format: '&b@ChatterBot &f%message%'

# ChatterBot will be assigned to a player for a certain amount of time if a trigger word is said
Trigger-Words: true

# How many seconds ChatterBot will be assigned to a player after they've said a trigger word
Trigger-Word-Timeout: 30

# List of words that enable ChatterBot when said in chat
Trigger-Word-List:
- admin
- OP
- staff
- malon
- owner
- kenpachi

# Change the type of bot ChatterBot uses
# Options:
# - CLEVERBOT
# - JABBERWACKY
ChatterBot-Type: CLEVERBOT
