broadcast:
  pre: '&9Stopping Villains'
  post: '&9Villains Stopped'
broadcastbackup:
  pre: '&9Calling For Backup'
  post: '&9Backup Received'
broadcastpurge:
  pre: '&9AutoPurging'
  post: '&9AutoPurge Complete'
autorestart:
  restarting: '&9Server is restarting'
  countdown: '&9Server will restart in {SECONDS} seconds'
worldregen:
  kickmessage: '&9Server is regenerating map, please come back later'
insufficentpermissions: '&cYou do not have access to that command.'
