# OnTime Configuration File
# Last Default YML Update: Jan 25, 2013
# Author: Edge209

###################################################
#  DO NOT CHANGE THE VERSION number for this file #
configVersion: 17
###################################################

# The name of your server
serverName: MyneCraft

# If purge is enabled users will be auto removed from stored file if they don't have enough play time / or have not been on for so long
purgeEnable: true

# minimum time in minutes someone has to be on for their data to be saved
purgeTimeMin: 10

# maximum time in days since last login before purge
purgeLoginDay: 60

# Enable if purged players should be auto-demoted
purgeDemotionEnable: false

# If purgeDemotion is enabled, this is target group for demotion
purgeDemotionGroup: default

# maximum length of 'top player' lists
topListMax: 10

# Enable if data should be saved to disk on scheduled event. Otherwise it will happen on server shutdown only
autoSaveEnable: true

# If auto file save is enabled above, how frequently (server ticks) should this be done.   (72000 = 1 hour)
autoSavePeriod: 72000

# Enable if backup versions of data files should be auto-created each day
autoBackupEnable: true

# If auto backup is enabled above, how many versions should be retained?
autoBackupVersions: 3

# Delay during OnTime enable to ensure it finished init AFTER vault, permissions, and econ plugins
# For most servers there is no need to change this (in seconds)
startupDelay: 0

# Enable/Disable detailed (daily/weekly/monthly) PLAYING TIME collection
collectPlayDetailEnable: true

# Enable/Disable detailed (daily/weekly/monthly) VOTE collection (requires MySQL)
collectVoteDetailEnable: false

# Enable/Disable detailed (daily/weekly/monthly) REFERRAL collection (requires MySQL)
collectReferDetailEnable: false

# Identify the starting day of each week for weekly reports and weekly rewards.  Valid Values: 1-7  where:
# 1=Sunday; 2=Monday; etc.
firstDayofWeek: 2

# Identify the starting day of each month for monthly reports, and monthly rewards. 
# Just in case you want to start in the middle for some strange reason..... and to help debug problems 
# Valid Values: 1-31  where: 1=1st; 2=2nd; etc.
firstDayofMonth: 1

# Enable if DAILY/WEEKLY/MONTLY reports should be auto-generated
autoReportEnable: true


# If 'autoReportEnable is true' then, enable various DAILY/WEEKLY/MONTHLY reports

dailyPlayReportEnable: true
weeklyPlayReportEnable: true
monthlyPlayReportEnable: true

# Report Storage sub-folder under /plugins/OnTime/
# '/' implies no sub-folder.  '/reports' is otherwise recommended
reportFolder: /

# Date format used in reports and in filename (if enabled below)
dateFilenameFormat: yyyy.MM.dd

# Enable date to be used in Report filenames (using format above)
dateInFilenameEnable: true

# If autoReportEnable is true, set the format of the reports: (Valid Settings: TXT, HTML, MYSQL)

reportFormat: TXT

# If autoReportEnable is true, set the duration (in days) that reports are retained before they are auto deleted

# Set any of the following to -1 to disable the auto deletion for that report type
# Recommendations: Daily:8; Weekly:36; Monthly:380; afk:15
#
dailyReportRetention: -1
weeklyReportRetention: -1
monthlyReportRetention: -1
afkReportRetention: -1

# Enable if Online player status should be tracked in MYSQL Table
onlineTrackingEnable: false

# If online tracking is enabled, set the refresh rate (in minutes)
onlineTrackingRefresh: 5

# Enable if log file should be created.
logEnable: false

# Detail to be included in OnTime logfile. 1=most detail ; 2=medium ; 3=least detail
logLevel: 1

# Detail to be shown on console. 1=most detail ;2= medium; 3=least detail
consoleLogLevel: 3

# Enable if OnTime Rewards system to be enabled
rewardsEnable: true

# Enable if Reward Notification Messages to players should be displayed
rewardNotifyEnable: true

# Enable if Reward Broadcast Messages should be sent to all online players
rewardBroadcastEnable: true

# Enable if players are allowed to be referred by other players, and 'referred by' rewards defined and issued
referredByEnable: true

# Enable if referred by usage should be tracked using permission strings. If referredByEnable (above) is true and
# dataStoage (below) is YML, this *MUST* remain true for referredBy to function.
referredByPermTrackEnable: true

# Max total OnTime (in hours) where player can still be referred by another. After they have been on this long, they can no longer claim
# a reference by another player.  Set to -1 for no limit.
referredByMaxTime: -1

# Enable if AFK status to be checked, and AFK time NOT counted
afkCheckEnable: true

# If AFK is enabled, max time (minutes) with no activity before player is considered AFK
afkTime: 1

# if AFK is enable, also enable this for AFK history collection and reporting
collectAfkEnable: false

# If AFK Collecting/Reporting is enabled, then set the period for AFK reporting/sorting.  
# Valid values are: Today, Week, Month (make sure only first letter is upper case)
afkReportPeriod: Week

# Selection of Data Storage Method.  Valid values= YML, MYSQL
dataStorage: YML

# MySQL - This must be enabled and properly set up if MySQL is to be used for data storage and/or
#		  data import is to be done from another plugin MySQL table.  (currently support for LogBlock is provided)
MySQL:
  enable: false
  host: localhost
  port: 3306
  user: root
  password: password
  database: minecraft
  table: ontime-players
  
# Top Player Rewards
#

# When should rewards be issued to the overall top (total OnTime) players?  Valid settings: 'disable', 'daily', 'weekly', and 'monthly'
totalTopPlayReward: weekly

# When should rewards be issued to the overall top voting players?  Valid settings: 'disable', 'daily', 'weekly', and 'monthly'
totalTopVoteReward: disable

# When should rewards be issued to the overall top referring players?  Valid settings: 'disable', 'daily', 'weekly', and 'monthly'
totalTopReferReward: disable

# When should rewards be issued to the overall top point earning players?  Valid settings: 'disable', 'daily', 'weekly', and 'monthly'
totalTopPointReward: disable


# Set 'true' if running OnTime in a single-server MC environment, or if this is designated the 'primary' server in 
# a multi-server MC environment where servers are sharing one MySQL database.  In the multi-server environment there
# should be only ONE of the servers designated as 'primary'
primaryServer: true

# Enable if OnTime Messaging will be used
messagesEnable: true
 
# Enable if OnTime Welcome Messages are to be displayed
welcomeEnable: true

# Enable if OnTime should check for latest plugin version (from bukkitdev)
updateCheckEnable: true


# Enable if 'loyalty' Points are going to be used
pointsEnable: false

# If 'pointsEnable' above is true, Enable this if negative 'loyalty' Points totals should be possible
negativePointsEnable: false


# END ontime/config.yml
