blacklist-enabled: false
queue-gui-name: '&9floAuction Queue'
allow-mobspawners: true
renamed-items-override: false
use-old-bid-logic: false
allow-bid-on-own-auction: false
log-auctions: false
default-starting-bid: 0
max-starting-bid: 10000000
default-bid-increment: 1
min-bid-increment: 1
max-bid-increment: 100
max-buynow: 10000000
expire-buynow-at-first-bid: false
default-auction-time: 60
min-auction-time: 15
max-auction-time: 120
allow-max-bids: true
allow-buynow: true
allow-early-end: false
allow-gamemode-creative: false
allow-damaged-items: true
allow-gamemode-change: false
allow-arenas: false
max-auction-queue-length: 2
min-auction-interval-secs: 10
auction-start-tax: 0
auction-end-tax-percent: 0
deposit-tax-to-user: ''
cancel-prevention-seconds: 15
cancel-prevention-percent: 50
anti-snipe: true
anti-snipe-prevention-seconds: 15
anti-snipe-extension-seconds: 10
allow-sealed-auctions: true
allow-unsealed-auctions: true
allow-renamed-items: true
broadcast-bid-updates: true
allow-auto-bid: true
suppress-countdown: false
allow-inferior-item-name-logic: false
auctionscope-change-check-interval: 20
banned-items:
- 7
- 383;63
taxed-items:
  '0': 100%
disabled-commands-participating:
- /ma join
- /mobarena join
- /arena join
disabled-commands-inscope: {}
banned-lore:
- mcMMO Ability Tool
auction-scopes:
  default:
    name: Default Auction Scope
    type: worlds
    worlds:
    - '1_9'
    config:
      disabled-commands-inscope: {}
name-blacklist:
- porn
- fuck
- shit
- nigger
- cunt
- wetback
- sex
- masturbate
- penis
- vagina
- wank
- tranny
- ass
- balls
- bearner
- bestiality
- bitch
- cock
- blowjob
- bondage
- busty
- boobs
- tits
- butt
- clit
- coon
- rape
- cum
- faggot
- escort
- hump
- bukkake
- hand job
- handjob
- incest
- pedo
- rapi
- topless
- boner
- shemale
- slut
- fingering
- gay
- dirty
- drug
- cocaine
- marijauna
- mary
- hump
- yiffy
