# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    survival112: -1
    survival112_nether: -1
    survival112_the_end: -1
    moblottery: -1
    skeeter_nether: -1
    newcity: -1
    elytralobby: -1
    skywarslobby: -1
    parkourmedium: -1
    formuladrift: -1
    speedforce: -1
    fortressofsolitude: -1
    runner: -1
    turfwars: -1
    hurdles: -1
    atlantis: -1
    crossfire: -1
    metropolis: -1
    longparkour: -1
    mazerunner: -1
    spleef: -1
    shootingrange: -1
    parkourhub: -1
    towerparkour: -1
    boatrace: -1
    pvpworldsforest: -1
    escaperoom: -1
    hurdles2: -1
    lavahop: -1
    freezetag: -1
    minecraftparkourmode: -1
    elytrapole: -1
    pvpworldsundergroundarmory: -1
    obstaclecourse: -1
    policeoffice: -1
    parkoureasy: -1
    vampirez: -1
    superherocity: -1
    hilariousrace: -1
    pvpparkour: -1
    titanstower: -1
    straightlineparkour: -1
    waynemanor: -1
    parkourhard: -1
    colosseumlobby: -1
    garbageworld: -1
    splegg: -1
    whitehouse: -1
    torture: -1
    deathrun: -1
    deathmachine: -1
    waterprison: -1
    flyingbattlearena: -1
    sprintparkour: -1
    greenfield_the_end: -1
    rollercoaster: -1
    rules: -1
    office: -1
    parksideprisonescape: -1
    fightclub: -1
    pvpworldsruins: -1
    flyingbattlelobby: -1
    elytraeasy: -1
    gotham: -1
    megaparkour: -1
    info: -1
    godlyparkour: -1
    chess: -1
    hallofjustice: -1
    marathon: -1
    techcombatknockbackgame: -1
    anarchy: -1
    infectiontag: -1
    elytrahard: -1
    verticalparkour: -1
    extremesumo: -1
    newminigamehub: -1
    skeeter_the_end: -1
    checkers: -1
    quickparkour: -1
    flappybirdparkour: -1
    deathdrop: -1
    skywars: -1
    heroicparkour: -1
    lasertag: -1
    initiation: -1
    alpha: -1
    pvpparkourlobby: -1
    infiniteparkour: -1
    turbotowers: -1
    colosseum: -1
    soccer: -1
    greenfield: -1
    spleeflobby: -1
    utopia: -1
    wallenpole: -1
    kingoftheladder: -1
    anarchy_nether: -1
    skeeter: -1
    elytramedium: -1
    elytrapvp: -1
    shortparkour: -1
    plots: -1
    overvoid: -1
    spawn: -1
    powerpicker: -1
    temple: -1
    labyrinth: -1
    pvpworldslobby: -1
    infinitycity: -1
  Claims:
    Mode:
      parkourhub: Disabled
      deathrun: Disabled
      parkoureasy: Disabled
      flyingbattlearena: Disabled
      colosseumlobby: Disabled
      skeeter_the_end: Disabled
      elytralobby: Disabled
      quickparkour: Disabled
      fightclub: Disabled
      escaperoom: Disabled
      office: Disabled
      initiation: Disabled
      deathmachine: Disabled
      pvpparkourlobby: Disabled
      pvpparkour: Disabled
      megaparkour: Disabled
      lasertag: Disabled
      wallenpole: Disabled
      godlyparkour: Disabled
      whitehouse: Survival
      towerparkour: Disabled
      sprintparkour: Disabled
      temple: Disabled
      flappybirdparkour: Disabled
      garbageworld: Disabled
      survival112_the_end: Survival
      marathon: Disabled
      rules: Disabled
      info: Disabled
      alpha: Disabled
      minecraftparkourmode: Disabled
      waynemanor: Disabled
      superherocity: Disabled
      gotham: Disabled
      hallofjustice: Disabled
      spawn: Disabled
      heroicparkour: Disabled
      overvoid: Disabled
      runner: Disabled
      atlantis: Survival
      shortparkour: Disabled
      anarchy: Disabled
      turbotowers: Disabled
      newminigamehub: Disabled
      elytramedium: Disabled
      flyingbattlelobby: Disabled
      skeeter: Disabled
      metropolis: Disabled
      titanstower: Disabled
      utopia: Disabled
      parksideprisonescape: Disabled
      splegg: Disabled
      skeeter_nether: Disabled
      infiniteparkour: Disabled
      checkers: Disabled
      spleef: Disabled
      skywarslobby: Disabled
      verticalparkour: Disabled
      deathdrop: Disabled
      freezetag: Disabled
      pvpworldsundergroundarmory: Disabled
      formuladrift: Disabled
      fortressofsolitude: Disabled
      techcombatknockbackgame: Disabled
      longparkour: Disabled
      straightlineparkour: Disabled
      vampirez: Disabled
      hurdles2: Disabled
      crossfire: Disabled
      labyrinth: Disabled
      spleeflobby: Disabled
      turfwars: Disabled
      lavahop: Disabled
      greenfield: Disabled
      infinitycity: Disabled
      chess: Disabled
      pvpworldsforest: Disabled
      kingoftheladder: Disabled
      powerpicker: Disabled
      pvpworldslobby: Disabled
      policeoffice: Disabled
      elytrapole: Disabled
      elytraeasy: Disabled
      elytrahard: Disabled
      newcity: Disabled
      speedforce: Disabled
      survival112: Survival
      obstaclecourse: Disabled
      infectiontag: Disabled
      parkourmedium: Disabled
      moblottery: Disabled
      anarchy_nether: Disabled
      waterprison: Disabled
      hurdles: Disabled
      parkourhard: Disabled
      greenfield_the_end: Disabled
      survival112_nether: Survival
      pvpworldsruins: Disabled
      torture: Disabled
      extremesumo: Disabled
      plots: Disabled
      boatrace: Disabled
      mazerunner: Disabled
      rollercoaster: Disabled
      soccer: Disabled
      shootingrange: Survival
      hilariousrace: Disabled
      colosseum: Disabled
      elytrapvp: Disabled
      skywars: Disabled
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 2000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLD_SPADE
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    PortalGenerationRequiresPermission: false
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
  Spam:
    Enabled: false
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 0
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      survival112: true
      survival112_nether: true
      survival112_the_end: true
      moblottery: false
      skeeter_nether: true
      newcity: false
      elytralobby: false
      skywarslobby: false
      parkourmedium: false
      formuladrift: false
      speedforce: true
      fortressofsolitude: true
      runner: false
      turfwars: true
      hurdles: false
      atlantis: true
      crossfire: true
      metropolis: false
      longparkour: false
      mazerunner: false
      spleef: false
      shootingrange: true
      parkourhub: false
      towerparkour: false
      boatrace: false
      pvpworldsforest: true
      escaperoom: false
      hurdles2: false
      lavahop: false
      freezetag: true
      minecraftparkourmode: false
      elytrapole: false
      pvpworldsundergroundarmory: true
      obstaclecourse: false
      policeoffice: true
      parkoureasy: false
      vampirez: false
      superherocity: true
      hilariousrace: false
      pvpparkour: false
      titanstower: true
      straightlineparkour: false
      waynemanor: true
      parkourhard: false
      colosseumlobby: false
      garbageworld: false
      splegg: true
      whitehouse: true
      torture: false
      deathrun: false
      deathmachine: false
      waterprison: true
      flyingbattlearena: true
      sprintparkour: false
      greenfield_the_end: false
      rollercoaster: false
      rules: false
      office: false
      parksideprisonescape: false
      fightclub: true
      pvpworldsruins: true
      flyingbattlelobby: false
      elytraeasy: false
      gotham: true
      megaparkour: false
      info: false
      godlyparkour: false
      chess: false
      hallofjustice: false
      marathon: false
      techcombatknockbackgame: true
      anarchy: false
      infectiontag: true
      elytrahard: false
      verticalparkour: false
      extremesumo: true
      newminigamehub: false
      skeeter_the_end: true
      checkers: false
      quickparkour: false
      flappybirdparkour: false
      deathdrop: false
      skywars: true
      heroicparkour: false
      lasertag: true
      initiation: false
      alpha: false
      pvpparkourlobby: false
      infiniteparkour: false
      turbotowers: false
      colosseum: true
      soccer: false
      greenfield: true
      spleeflobby: false
      utopia: false
      wallenpole: false
      kingoftheladder: true
      anarchy_nether: true
      skeeter: true
      elytramedium: false
      elytrapvp: true
      shortparkour: false
      plots: false
      overvoid: false
      spawn: false
      powerpicker: false
      temple: false
      labyrinth: false
      pvpworldslobby: false
      infinitycity: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers: true
    AllowFlintAndSteelNearOtherPlayers: true
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: false
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: false
  AdminsGetSignNotifications: false
  SmartBan: false
  Mute New Players Using Banned Words: false
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS
    - LONG_GRASS
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - THIN_GLASS
    - WOOD
    - WOOL
    - SNOW
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Mods:
    BlockIdsRequiringAccessTrust: []
    BlockIdsRequiringContainerTrust:
    - 99999:*:Example - ID 99999, all data values.
    BlockIdsExplodable: []
    PlayersIgnoringAllClaims: []
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
