# 
# Whether or not resourcepack file hashes should be generated on startup:
debug: true
autogeneratehashes: true
messages:
  usepack: You now use the pack %pack%!
  packlisthead: 'Packs available to you:'
  nopacks: No packs found!
packs:
  razul:
    url: http://mynecraft.servegame.com/razul.zip
    hash: 7445da964654da8c95ede7b581e6ec6a1b41c9ed
    format: 0
    restricted: false
    permission: worldresourcepacks.pack.razul
  greenfield:
    url: http://mynecraft.servegame.com/superherocity.zip
    hash: 92dd9d2119d582537c71d3aba90cb92e342031e7
    format: 1
    restricted: false
    permission: worldresourcepacks.pack.greenfield
  survival:
    url: http://mynecraft.servegame.com/survivalresourcepack.zip
    hash: bca58339e5c91338ea7e7a0ec2d09d7f004c4100
    format: 3
    restricted: false
    permission: worldresourcepacks.pack.survival
  emptypack:
    url: http://cdn.moep.tv/files/Empty.zip
    hash: 81ffbd1712afe8cdf138b570c0fc9934742c33c1
    format: 0
    restricted: false
    permission: worldresourcepacks.pack.emptypack
empty: survival
server:
  pack: survival
worlds:
  greenfield:
    pack: greenfield
  survival:
    pack: survival
  razul:
    pack: razul
